language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.00 PINS=solvuu-build
  - OCAML_VERSION=4.01 PINS=solvuu-build
  - OCAML_VERSION=4.02 PINS=solvuu-build
  - OCAML_VERSION=4.03 PINS=solvuu-build
  - OCAML_VERSION=4.04 PINS=solvuu-build
os:
  - linux
  - osx
